name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        with:
          github_token: ${{ secrets.TOKODEMO_ACCESS_TOKEN }}
          publish_dir: ./
