name: Deploy Website

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Deploy to GitHub Pages - test
        uses: actions/deploy-pages@v4.0.5
        with:
          github_token: ${{ secrets.TOKODEMO_ACCESS_TOKEN }}
          publish_dir: ./
